package com.example.data.database

import androidx.room.*
import kotlinx.coroutines.flow.Flow

@Entity(tableName = "photos")
data class PhotoEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val uri: String, // Image network URL, local database simulated file reference, or drawable resource
    val title: String,
    val timestamp: Long,
    val location: String,
    val isVideo: Boolean,
    val durationString: String? = null, // e.g. "0:15"
    val fileSizeString: String, // e.g. "3.5 MB"
    val isBackedUp: Boolean = false,
    val isLockedInVault: Boolean = false,
    val tags: String, // comma separated list
    val faces: String, // comma separated list
    val objects: String, // comma separated list
    val isFavorite: Boolean = false,
    val aiCaption: String = "",
    val aiRating: Float = 4.5f,
    val fileHash: String = ""
)

@Entity(
    tableName = "cached_media",
    foreignKeys = [
        ForeignKey(
            entity = PhotoEntity::class,
            parentColumns = ["id"],
            childColumns = ["photoId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index(value = ["photoId"], unique = true)]
)
data class CachedMediaEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val photoId: Int,
    val localFilePath: String, // Path in local cache directory
    val cachedSizeBytes: Long,
    val cacheTimestamp: Long,
    val mimeType: String,
    val isThumbnailOnly: Boolean = false,
    val isAvailableOffline: Boolean = true
)

@Dao
interface CachedMediaDao {
    @Query("SELECT * FROM cached_media WHERE photoId = :photoId LIMIT 1")
    suspend fun getCacheByPhotoId(photoId: Int): CachedMediaEntity?

    @Query("SELECT * FROM cached_media ORDER BY cacheTimestamp DESC")
    fun getAllCachedMediaFlow(): Flow<List<CachedMediaEntity>>

    @Query("SELECT * FROM cached_media")
    suspend fun getAllCachedMedia(): List<CachedMediaEntity>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertCache(cache: CachedMediaEntity): Long

    @Query("DELETE FROM cached_media WHERE photoId = :photoId")
    suspend fun deleteCacheByPhotoId(photoId: Int)

    @Query("DELETE FROM cached_media")
    suspend fun clearAllCache()

    @Query("SELECT SUM(cachedSizeBytes) FROM cached_media")
    fun getTotalCachedBytesFlow(): Flow<Long?>

    @Query("SELECT COUNT(*) FROM cached_media")
    suspend fun getCachedCount(): Int
}

@Entity(tableName = "ai_memories")
data class AiMemoryAlbumEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val title: String,
    val description: String,
    val coverPhotoUri: String,
    val dateCreated: Long = System.currentTimeMillis(),
    val photoIdsString: String, // comma separated photo IDs, e.g. "1,2,3"
    val memoryType: String, // "DATE", "LOCATION", "EVENT"
    val triggerPattern: String, // e.g. "Location: India", "Calendar Day", "Theme: Portrait Gatherings"
    val isAutoGenerated: Boolean = true
)

@Dao
interface AiMemoryDao {
    @Query("SELECT * FROM ai_memories ORDER BY dateCreated DESC")
    fun getAllMemoriesFlow(): Flow<List<AiMemoryAlbumEntity>>

    @Query("SELECT * FROM ai_memories")
    suspend fun getAllMemories(): List<AiMemoryAlbumEntity>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertMemory(memory: AiMemoryAlbumEntity): Long

    @Query("DELETE FROM ai_memories WHERE id = :id")
    suspend fun deleteMemoryById(id: Int)

    @Query("DELETE FROM ai_memories")
    suspend fun clearAllMemories()

    @Query("SELECT COUNT(*) FROM ai_memories")
    suspend fun getMemoriesCount(): Int
}

@Dao
interface PhotoDao {
    @Query("SELECT * FROM photos ORDER BY timestamp DESC")
    fun getAllPhotos(): Flow<List<PhotoEntity>>

    @Query("SELECT * FROM photos WHERE isLockedInVault = 0 ORDER BY timestamp DESC")
    fun getPublicPhotos(): Flow<List<PhotoEntity>>

    @Query("SELECT * FROM photos WHERE isLockedInVault = 1 ORDER BY timestamp DESC")
    fun getVaultPhotos(): Flow<List<PhotoEntity>>

    @Query("SELECT * FROM photos WHERE isFavorite = 1 ORDER BY timestamp DESC")
    fun getFavoritePhotos(): Flow<List<PhotoEntity>>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertPhoto(photo: PhotoEntity): Long

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertPhotos(photos: List<PhotoEntity>)

    @Update
    suspend fun updatePhoto(photo: PhotoEntity)

    @Query("DELETE FROM photos WHERE id = :id")
    suspend fun deletePhotoById(id: Int)

    @Query("UPDATE photos SET isBackedUp = :isBackedUp WHERE id = :id")
    suspend fun updateBackupStatus(id: Int, isBackedUp: Boolean)

    @Query("UPDATE photos SET isLockedInVault = :isLockedInVault WHERE id = :id")
    suspend fun updateVaultStatus(id: Int, isLockedInVault: Boolean)

    @Query("UPDATE photos SET isFavorite = :isFavorite WHERE id = :id")
    suspend fun updateFavoriteStatus(id: Int, isFavorite: Boolean)

    @Query("SELECT COUNT(*) FROM photos")
    suspend fun getPhotoCount(): Int
}

@Database(entities = [PhotoEntity::class, CachedMediaEntity::class, AiMemoryAlbumEntity::class], version = 4, exportSchema = false)
abstract class PhotoDatabase : RoomDatabase() {
    abstract fun photoDao(): PhotoDao
    abstract fun cachedMediaDao(): CachedMediaDao
    abstract fun aiMemoryDao(): AiMemoryDao

    companion object {
        @Volatile
        private var INSTANCE: PhotoDatabase? = null

        fun getDatabase(context: android.content.Context): PhotoDatabase {
            return INSTANCE ?: synchronized(this) {
                val instance = androidx.room.Room.databaseBuilder(
                    context.applicationContext,
                    PhotoDatabase::class.java,
                    "photoverse_database"
                )
                .fallbackToDestructiveMigration()
                .build()
                INSTANCE = instance
                instance
            }
        }
    }
}
